// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'item-info-row-arxiv-id-label'
  | 'item-info-row-translation-status-label'
  | 'item-section-translation-head-text'
  | 'item-section-translation-sidenav-tooltip'
  | 'menuitem-clear-state'
  | 'menuitem-recompile'
  | 'menuitem-retranslate'
  | 'menuitem-search-arxiv'
  | 'menuitem-translate'
  | 'menuitem-translate-batch'
  | 'menuitem-view-status'
  | 'pref-help'
  | 'pref-output-dir'
  | 'pref-output-section'
  | 'pref-parallelism'
  | 'pref-service-section'
  | 'pref-service-url'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish';
