// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "serviceUrl": string;
      "apikey": string;
      "apiEndpoint": string;
      "model": string;
      "xelatexPath": string;
      "parallelism": number;
      "outputDir": string;
      "maxRetries": number;
    };
  }
}
